<?php
/**
 * @var $block \Pagaleve\Payment\Block\Info\Pagaleve
 */
$order = $block->getOrder();
?>
<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Pagaleve')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method pagaleve">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('PIX paid in 4x')) ?></span>
            </div>
        </div>
    </div>
</section>
