<?php

/**
 * @author      FCamara - Formação e Consultoria <contato@fcamara.com.br>
 * @author      Guilherme Miguelete <guilherme.miguelete@fcamara.com.br>
 * @license     Pagaleve Tecnologia Financeira | Copyright
 * @copyright   2022 Pagaleve Tecnologia Financeira (http://www.pagaleve.com.br)
 *
 * @link        http://www.pagaleve.com.br
 */
/**
 * @var $block \Pagaleve\Payment\Block\Info\Pagaleve
 */
$order = $block->getOrder();
?>
<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method pagaleve">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Pagaleve - PIX UpFront')) ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-additional" style="min-width: 400px;">
                    <strong><?= __('Checkout ID') ?>: </strong><?= $order->getData('pagaleve_checkout_id') ?>
                </div>
                <div class="order-payment-additional" style="min-width: 400px;">
                    <strong><?= __('Payment ID') ?>: </strong><?= $order->getData('pagaleve_payment_id') ?>
                </div>
                <?php if ($order->getData('pagaleve_expiration_date')) : ?>
                    <div class="order-payment-additional" style="min-width: 400px;">
                        <strong><?= __('Release Date') ?>: </strong>
                        <?= $block->formatDate($order->getData('pagaleve_expiration_date'), 3, true) ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>